[[headers]]
      for = "/*"
            [headers.values]
            Access-Control-Allow-Origin = "*"
      
      for = "/*.ts"
            [headers.values]
            Content-Type = "Application/Typescript"